# IonScan Config
DEFAULT_IFACE=""
WEBHOOK_URL=""
LOG_LEVEL="INFO"

# Scan defaults
SCAN_TIMEOUT=300
SCAN_RATE=T4

# Module Enablement
MODULE_RECON_ENABLED=true
MODULE_WIRELESS_ENABLED=true
MODULE_EXPLOIT_ENABLED=true
MODULE_UTILS_ENABLED=true
MODULE_REPORT_ENABLED=true